### ISSUE TITLE
Indentation error on kotlin-mode

### ISSUE THREAD

**Issue by marcos-cezar** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#14]
When I'm typing an if, while or anything that opens a block of commands inside the main function. When i hit enter after the "if (exp) {" the close "}" is inserted and not indented. It can be seen on the image below.

![kotlin-mode-indentation-error](https://cloud.githubusercontent.com/assets/1326526/19867449/06018e34-9f8b-11e6-9617-0d29e1d986b5.png)

I'm using Emacs 25.1.50.1 and this packages:

cask
color-theme-sanityinc-tomorrow
expand-region
ace-jump-mode
flx
flx-ido
yasnippet
projectile
helm-projectile
ido-ubiquitous
ido-vertical-mode
multiple-cursors
smartparens
magit
css-eldoc
ido-at-point
guide-key
simple-httpd
restclient
whitespace-cleanup-mode
elisp-slime-nav
exec-path-from-shell
ag
emmet-mode
js2-mode
js2-refactor
tern
smex
markdown-mode
browse-kill-ring
shell-command
dired+
vlf
scala-mode
sbt-mode
quickrun
dash-at-point
web-mode
undo-tree
ggtags
helm-gtags
ensime
company
company-quickhelp
avy
smart-mode-line
beacon
aggressive-indent
gradle-mode
wgrep
pt
icicles
o-blog
cider
clojure-mode
powerline
spaceline
peep-dired
use-package
groovy-mode
smart-comment
ace-window
zoom-frm
hydra
which-key
kotlin-mode

**Comment by russel** [comment]
Typing your code fragment into Emacs 25.1.1 on Debian Sid, I find that the alignment is adjusted on pressing newline after the }.

**Comment by gregghz** [comment]
This is an issue I've been aware of for a while. It's definitely a bug. I haven't seen any other major mode behave like this (scala-mode is what I spend most of my time in, for example).

**Comment by gregghz** [comment]
This should be solved with https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/issues/14

**Comment by ldelelis** [comment]
Running Emacs 25.2.1 with the Spacemacs distribution, the bracing indentation appears to work correctly now.

![2017-08-05-145913_1904x1046_scrot](https://user-images.githubusercontent.com/20250323/28997592-d9ac3908-79ee-11e7-8291-2227cbf5aa20.png)

This was a test run with `kotlin-tab-width` set to 4.
