### ISSUE TITLE
Default indentation is 8 spaces

### ISSUE THREAD

**Issue by russel** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#15]
It seems that the default indentation for Kotlin mode is 8 spaces. Is this the right default?

There appears to be no examples of changing the various defaults.

**Comment by gregghz** [comment]
I believe it should be 4 spaces but in certain nested cases (like when indenting parameter lists) it uses 2x the default indentation level.

There currently is no option for either of these things in kotlin-mode.

**Comment by tituomin** [comment]
Set the variable kotlin-tab-width to change the default.

**Comment by shaleh** [comment]
But why is it 8 when the community standard is 4??

**Comment by russel** [comment]
Of course the right character for indent is tab. At least Go uses that, but Python, Rust, etc. have a de facto standard of 4 spaces. :-(

**Comment by DarrienG** [comment]
I swear plugins do this to make you fiddle with your .emacs more. The only code style I've seen with 8 spaces default is GNU C. Insane default.

**Comment by gregghz** [comment]
the default was changed to 4 https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/commit/ab610996820b5cbdb032edbf8747661131603ab8
