### ISSUE TITLE
Please remove obsolete 'default-tab-width' variable.

### ISSUE THREAD

**Issue by kawabata** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#17]
There is a line

(defcustom kotlin-tab-width default-tab-width

which causes an error in currently developing Emacs 26, as
'default-tab-width' is obsolete since Emacs 23 and will be removed
in upcoming Emacs 26.

I hope 'default-tab-width' would be  changed to "tab-width" instead, 
as mentioned in current Emacs 25 'default-tab-width' documentation.

**Comment by ilanpillemer** [comment]
+1 as this causes issues if you use emacs built from HEAD. I had to add a line to my `.emacs` for it to install.

```
;; kotlin-mode wants this set
(setq default-tab-width 4)
(use-package kotlin-mode
  :config
  :pin melpa
  )
```

**Comment by gregghz** [comment]
Fixed via https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/commit/ebcf6f3730f455894ebb7ed8e42950f66e8e1c1d
