### ISSUE TITLE
Alternative indentation engine

### ISSUE THREAD

**Issue by 7ocb** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#24]
Hello!

I don't like how currently indentation works, it does not handle the multiline lists, so I implemented [my own](https://github.com/7ocb/my-elk-kotlin-indent).

It's not ideal, but maybe it will be interesting to you.

Thanks for your work! (:

**Comment by ice1000** [comment]
Another problem related to indentation:

I have:
```kotlin
fun f() =
    println("ice1000")
```

I press <kbd>Tab</kbd> at the second line of the code above, and it becomes

```kotlin
fun f() =
println("ice1000")
```

This should be a bug.

**Comment by ice1000** [comment]
@gergoerdi @purcell @russel @jasonm23

**Comment by gregghz** [comment]
indentation was heavily refactored. Can you check the new implementation and see if it improves your experience? Please file bugs against specific issues when you find any. @ice1000 I believe this is still an issue, probably the same problem as https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/issues/34

**Comment by ice1000** [comment]
Cool!

**Comment by gregghz** [comment]
@ice1000 I think this will be fixed by https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/pull/53
