### ISSUE TITLE
Add send-{block,buffer,line,region}-and-focus functions

### ISSUE THREAD

**Issue by trevorsummerssmith** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#26]
It is nice to send code to the repl and then have the cursor be there. Specifically it would be nice to have the following functions:
kotlin-send-block-and-focus
kotlin-send-buffer-and-focus
kotlin-send-line-and-focus
kotlin-send-region-and-focus

I have code locally that does this but wanted to see if this was something ya'll would be interested in before I sent a PR. Thanks for the mode!

**Comment by gregghz** [comment]
This sounds like a great feature. Send a PR so we can look it over!

**Comment by trevorsummerssmith** [comment]
@gregghz wanted to make sure you saw the PR, and if there is anything else you need from me. Thanks!
