### ISSUE TITLE
Indentation incorrect for `if` statements without braces

### ISSUE THREAD

**Issue by timmc** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#34]
In the following code, the second line should be indented:
```kotlin
if (true)
    println("true")
```

However, kotlin-mode indents it like so:
```kotlin
if (true)
println("true")
```

**Comment by ted-tanner** [comment]
This was fixed by commit [f8b7b36](https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/commit/f8b7b3648e230368fc019b63263dff874ac255cd) and can be closed.
