### ISSUE TITLE
Automatically enable kotlin mode on .kts files

### ISSUE THREAD

**Issue by mikegolod** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#35]

**Comment by Willyfrog** [comment]
I believe this happens already, unless you have some custom config. See:

https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/blob/master/kotlin-mode.el#L416

**Comment by gregghz** [comment]
Fixed by https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/pull/36
