### ISSUE TITLE
publish the package to elpa or some package repo ?

### ISSUE THREAD

**Issue by eggcaker** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#4]

**Comment by jasonm23** [comment]
I will do this today!

**Comment by gregghz** [comment]
did this ever happen?

**Comment by jasonm23** [comment]
Still pending

**Comment by gregghz** [comment]
@jasonm23 consider this fork instead: https://github.com/gregghz/kotlin-mode

I've incorporated all the PRs from upstream and improved indentation. Feel free to submit issue there as well. I plan to continue maintaining it.

**Comment by jasonm23** [comment]
There is a PR open on MELPA, for this repo, please orchestrate change with the submitter.

Note: the issues section on your fork is disabled, please enable it.

I think this branch appears to be abandoned.

**Comment by gregghz** [comment]
I just enabled issues. Thanks for letting me know.

**Comment by jasonm23** [comment]
Good news!

**Comment by russel** [comment]
@jasonm23 @gregghz Rather than just shift from one person to another, I propose an organization with three or four owners is set up to own a mainline repository and take responsibility for things like MELPA presence?

**Comment by jasonm23** [comment]
I am happy to be a contributor to this repo.  I'm all for any plan which gets this mode onto MELPA.

**Comment by russel** [comment]
The process for getting modes into MELPA is easy and straightforward. It is though a very good idea to have the right base from the outset. My feeling is that there should be an organization with three or four owners so that no matter who is involved with forks, pull requests, management, etc. the mainline repository is the same for the short, medium, and long term.

**Comment by gregghz** [comment]
https://github.com/melpa/melpa/pull/3992

FWIW, kotlin-mode is already published on melpa as gregghz/kotlin-mode. The referenced PR updates it to this repo. I'll close once it's merged.
