### ISSUE TITLE
Call for a new maintainer

### ISSUE THREAD

**Issue by quantumman** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#5]
Hey everyone.

I am looking for a new maintainer of this project.

For those of you that has been following this project, you noteiced that my activity
stopped a year ago. To be honest, I never exptected someone found this project, and have no time to spend it now. 

If anyone is interested that would be very helpful!

Thanks.

**Comment by gregghz** [comment]
I might be interested. What info do you need from me?

**Comment by gregghz** [comment]
https://github.com/gregghz/kotlin-mode

Here's my fork. I've already merged outstanding PRs from upstream and improved indentation.

**Comment by russel** [comment]
@quantumman If you make an organization, transfer the repository to the organization, and add a couple of extra owners of the organization (I am happy to volunteer, and it sounds like @gregghz might as well) then things can progress quite naturally from there.

**Comment by gregghz** [comment]
That sounds great to me :)

**Comment by gregghz** [comment]
If there's no word from the current owner, I wouldn't mind seeing things up as well.

**Comment by russel** [comment]
@gregghz I have emailed @quantumman My feeling is that it would be best to base the organization mainline repository on this original rather than your fork, but if that is not possible then working with your fork to create an organization works for me.

**Comment by gregghz** [comment]
Thanks @russel. Let me know what you hear. If we do end up basing the org in this branch I'll likely just submit a PR pretty quickly against my branch anyway. So either way is fine. 

As soon as you have the org set up, love to be a member. In addition, the sooner the better so we can get the melpa stuff in line. I already created a PR for my branch, but I'd be happy to switch it as soon as we have somewhere else to point it.

**Comment by russel** [comment]
@gregghz I have create the Emacs-Kotlin-Mode-Maintainers organization and invited you to be an owner. I suggest we work with your fork of this repository as the mainline and patch things up if others get interested. I propose we move all activity to the new organization.

**Comment by quantumman** [comment]
Sorry, I didn't notice mentions.
I will transfer this repository to Emacs-Kotlin-Mode-Maintainers if nobody disagree @russel 's proposal.

**Comment by russel** [comment]
@quantumman That would be great. There are ongoing discussions of names for organization and repository, but that can all be handled even after transfer.

Thanks for starting this work off, I'm sorry you are feeling not able to continue to contribute just now. Hopefully you will sign up as an owner of the organization so that you can come back to this in the future.

**Comment by quantumman** [comment]
@russel @gregghz

I am sorry about replying late. I have transferred coastline-mode to the Emacs-Kotlin-Mode-Maintenance a little while ago. I no longer maintained this repo, but  be happy if you're going to grow this repo. 

Thanks.
