### ISSUE TITLE
Bugged highlighting on `out`

### ISSUE THREAD

**Issue by ajc2** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#51]
The highlighter bugs when it encounters \`out\`, coloring the rest of the code as if it were a string. No other backticked identifier seems to do this.
![2019-12-06T01:41:31-05:00](https://user-images.githubusercontent.com/12587624/70302036-07ce1380-17ca-11ea-9699-03f48696b23f.png)

**Comment by 12Me21** [comment]
This happens whenever there are an odd number of characters inside ` `` `

**Comment by t-gebauer** [comment]
Removing the following `when` expression fixes this issue
```diff
diff --git a/kotlin-mode-lexer.el b/kotlin-mode-lexer.el
index 2548ff0..e6150c4 100644
--- a/kotlin-mode-lexer.el
+++ b/kotlin-mode-lexer.el
@@ -148,14 +148,7 @@ the scan stops where the level becomes zero."
                              'syntax-table
                              (string-to-syntax "|"))
           (kotlin-mode--syntax-propertize-end-of-string end quotation)
-          (put-text-property start (point) 'syntax-multiline t)
-
-          (when (equal quotation "`")
-            ;; Backquotes cannot be escaped. So declares the backslashes in
-            ;; the identifier are not a escape-syntax characters.
-            (put-text-property (1+ start) (1- (point))
-                               'syntax-table
-                               (string-to-syntax "|")))))
+          (put-text-property start (point) 'syntax-multiline t)))
 
        ((equal "//" (match-string-no-properties 0))
         (goto-char (match-beginning 0))
```
But as the comment explains: this would allow another edge case to render incorrectly
```kotlin
fun `foo\`() { }
```

However, I don't think, that that is even a problem. `\` is not a valid character in identifiers. So, no sane Kotlin code should contain such an expression.

**Comment by taku0** [comment]
`\` is valid character in private identifiers of Kotlin/JS and all identifiers of Kotlin/Native.

Example:

```
fun foo() {
  val `x\` = 1

  print(`x\`)
}
```

https://kotlinlang.org/docs/reference/grammar.html#Identifier

**Comment by taku0** [comment]
Changing `(string-to-syntax "|")` to `(string-to-syntax "w")` will fix this.
