### ISSUE TITLE
Please a LICENSE file documenting the license that governs the distribution

### ISSUE THREAD

**Issue by gutron** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#60]
Some of the source files include a header that identifies the GPL as the license for this software, but other files have no such header, leading one to wonder whether the GPL applies only to some files and not to others.  Please clear this up by adding a LICENSE file, containing the relevant version of the GPL, into the distribution.

**Comment by sten0** [comment]
It looks like this was resolved by 86b94d7d343d1022225a97db830c3a1a61dd57c8
