### ISSUE TITLE
Adding kotlin-mode to NonGNU ELPA

### ISSUE THREAD

**Issue by phikal** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#62]
Hey,

I am currently working on adding a few major modes to [NonGNU ELPA](https://elpa.nongnu.org), including kotlin-mode. The main difference to MELPA is that ELPA searches the master branch to find the last commit that bumps the `Version` attribute in the [package header of the main file](https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/blob/master/kotlin-mode.el#L5-7). As there currently is no Version attribute, no package is generated in the default repository. Would it be possible to add and update such an attribute in the future, whenever a new release is made?

**Comment by gregghz** [comment]
@phikal thanks for the interest! You are welcome to add the version attribute via a PR, I'll have no issues approving that. I'm fine with any versioning, not sure if there are requirements but a simple 1.0.0 or even just 1 would be fine with me.

**Comment by phikal** [comment]
In general the only requirement should be that `version-list` can parse the attribute value.
