### ISSUE TITLE
Outdated "stable" version

### ISSUE THREAD

**Issue by doublep** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#68]
I have installed version 1.0.0 from NonGNU ELPA, but it is apparently horribly outdated. Please either keep stable versions up-to-date (of course they are not meant to include all the latest changes, but at least bugfixes), or pull it from NonGNU ELPA altogether, to avoid confusing people who use that PA.

**Comment by gregghz** [comment]
fixed via https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/commit/d92c3b773473e9fe15f61f6177e4fbf097aadd05
