### ISSUE TITLE
Indentation command moves point

### ISSUE THREAD

**Issue by doublep** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#69]
Place point at the end of any line. Press `TAB`. Point moves to the first non-whitespace character on that line (whether it has been reindented or not). This is unlike *all* standard Emacs modes and makes editing very annoying by breaking established habits.

I.e. (here `@` denotes the point):

    if (true)@

press `TAB`; becomes:

    @if (true)

**Comment by gregghz** [comment]
> This is unlike all standard Emacs modes

true. Unfortunately I don't really have the emacs know-how to address this immediately and likely won't in the near term. I suspect there's some block of code that should be wrapped in a `save-excursion` call but I'm unsure if that's the case and if it is, I'm unsure which code needs it.

As a quick check, can you let me know what function is being called when you press `TAB`? I'm using doom emacs and with or without evil mode enabled, tab just adds a tab character for me in kotlin-mode, it does not re-indent the line.

I'd, of course, be happy to look at any PRs with a fix.

**Comment by doublep** [comment]
It runs `indent-for-tab-command` here.

**Comment by sten0** [comment]
@gregghz By default Emacs calls `indent-for-tab-command`.  One can temporarily disable all user and site packages and configuration to check upstream defaults by running `emacs -q -Q`.

> I'd, of course, be happy to look at any PRs with a fix.

It looks like either #38 or #53 (both need rebasing) would resolve this bug.

**Comment by gregghz** [comment]
fixed via https://github.com/Emacs-Kotlin-Mode-Maintainers/kotlin-mode/pull/70
