### ISSUE TITLE
Testsuite/build failure on Debian Unstable/Ubuntu 22.04 with latest commits

### ISSUE THREAD

**Issue by JPeisach** [Emacs-Kotlin-Mode-Maintainers/kotlin-mode#71]
`jpeisach@Joshua-PC ~/D/kotlin-mode (master)> gbp buildpackage -us -uc --git-ignore-new
gbp:info: Creating /home/jpeisach/Desktop/kotlin-mode_0.0~git20220527.99499e1.orig.tar.xz
gbp:info: Performing the build
 dpkg-buildpackage -us -uc -ui -i -I
dpkg-buildpackage: info: source package kotlin-mode
dpkg-buildpackage: info: source version 0.0~git20220527.99499e1-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Joshua Peisach <itzswirlz2020@outlook.com>
 dpkg-source -i -I --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: applying 0001-declare-correct-MELPA-version.patch
 debian/rules clean
dh clean --with elpa
   dh_auto_clean
	make -j4 clean
make[1]: Entering directory '/home/jpeisach/Desktop/kotlin-mode'
/bin/sh: 1: cask: not found
rm -rf dist *.elc
make[1]: Leaving directory '/home/jpeisach/Desktop/kotlin-mode'
   dh_clean
 dpkg-source -i -I -b .
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building kotlin-mode using existing ./kotlin-mode_0.0~git20220527.99499e1.orig.tar.xz
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: building kotlin-mode in kotlin-mode_0.0~git20220527.99499e1-1.debian.tar.xz
dpkg-source: info: building kotlin-mode in kotlin-mode_0.0~git20220527.99499e1-1.dsc
 debian/rules binary
dh binary --with elpa
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/jpeisach/Desktop/kotlin-mode'
Ignoring upstream Makefile and building/installing with dh-elpa.
make[1]: Leaving directory '/home/jpeisach/Desktop/kotlin-mode'
   dh_elpa_test
	emacs -batch -Q -l package --eval "(add-to-list 'package-directory-list \"/usr/share/emacs/site-lisp/elpa\")" --eval "(add-to-list 'package-directory-list \"/usr/share/emacs/site-lisp/elpa-src\")" -f package-initialize -L . -L test -l test/kotlin-mode-test.el --eval \(ert-run-tests-batch-and-exit\)
Running 6 tests (2022-07-05 20:15:42-0400, selector ‘t’)
   passed  1/6  kotlin-mode--chained-methods (0.000637 sec)
   passed  2/6  kotlin-mode--ignore-comment-test (0.000607 sec)
   passed  3/6  kotlin-mode--indent-comment-at-bob--test (0.000433 sec)
Test kotlin-mode--sample-test backtrace:
  signal(ert-test-failed (((should (equal expected-line (thing-at-poin
  ert-fail(((should (equal expected-line (thing-at-point 'line))) :for
  (if (unwind-protect (setq value-82 (apply fn-80 args-81)) (setq form
  (let (form-description-84) (if (unwind-protect (setq value-82 (apply
  (let ((value-82 'ert-form-evaluation-aborted-83)) (let (form-descrip
  (let* ((fn-80 #'equal) (args-81 (condition-case err (let ((signal-ho
  (let ((expected-line (thing-at-point 'line))) (beginning-of-line) (d
  (while (not (eobp)) (let ((expected-line (thing-at-point 'line))) (b
  (progn (insert-file-contents "test/sample.kt") (goto-char (point-min
  (unwind-protect (progn (insert-file-contents "test/sample.kt") (goto
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-b
  (lambda nil (let ((temp-buffer (generate-new-buffer " *temp*"))) (sa
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name kotlin-mode--sample-test :documentati
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests ... :test-map
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  eval((ert-run-tests-batch-and-exit) t)
  command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc
  command-line()
  normal-top-level()
Test kotlin-mode--sample-test condition:
    (ert-test-failed
     ((should
       (equal expected-line
	      (thing-at-point ...)))
      :form
      (equal
       #("    print(\"First argument: ${args[0]}\")
" 10 11
(syntax-table ... syntax-multiline t)
11 27
(syntax-multiline t)
27 28
(kotlin-property--matching-bracket 964 syntax-multiline t)
28 29
(syntax-table ... kotlin-property--matching-bracket 964 syntax-multiline t)
29 36
(syntax-multiline t)
36 37
(syntax-table ... kotlin-property--matching-bracket 955 syntax-multiline t)
37 38
(syntax-table ... syntax-multiline t))
       #("        print(\"First argument: ${args[0]}\")
" 14 15
(syntax-table ... syntax-multiline t)
15 31
(syntax-multiline t)
31 32
(kotlin-property--matching-bracket 968 syntax-multiline t)
32 33
(syntax-table ... kotlin-property--matching-bracket 968 syntax-multiline t)
33 40
(syntax-multiline t)
40 41
(syntax-table ... kotlin-property--matching-bracket 959 syntax-multiline t)
41 42
(syntax-table ... syntax-multiline t)))
      :value nil :explanation
      (arrays-of-different-length 40 44
				  #("    print(\"First argument: ${args[0]}\")
" 10 11
(syntax-table ... syntax-multiline t)
11 27
(syntax-multiline t)
27 28
(kotlin-property--matching-bracket 964 syntax-multiline t)
28 29
(syntax-table ... kotlin-property--matching-bracket 964 syntax-multiline t)
29 36
(syntax-multiline t)
36 37
(syntax-table ... kotlin-property--matching-bracket 955 syntax-multiline t)
37 38
(syntax-table ... syntax-multiline t))
				  #("        print(\"First argument: ${args[0]}\")
" 14 15
(syntax-table ... syntax-multiline t)
15 31
(syntax-multiline t)
31 32
(kotlin-property--matching-bracket 968 syntax-multiline t)
32 33
(syntax-table ... kotlin-property--matching-bracket 968 syntax-multiline t)
33 40
(syntax-multiline t)
40 41
(syntax-table ... kotlin-property--matching-bracket 959 syntax-multiline t)
41 42
(syntax-table ... syntax-multiline t))
				  first-mismatch-at 4)))
   FAILED  4/6  kotlin-mode--sample-test (0.086361 sec)
   passed  5/6  kotlin-mode--single-level-indent-test (0.000305 sec)
   passed  6/6  kotlin-mode--top-level-indent-test (0.000486 sec)

Ran 6 tests, 5 results as expected, 1 unexpected (2022-07-05 20:15:42-0400, 0.250766 sec)

1 unexpected results:
   FAILED  kotlin-mode--sample-test

dh_elpa_test: error: emacs -batch -Q -l package --eval "(add-to-list 'package-directory-list \"/usr/share/emacs/site-lisp/elpa\")" --eval "(add-to-list 'package-directory-list \"/usr/share/emacs/site-lisp/elpa-src\")" -f package-initialize -L . -L test -l test/kotlin-mode-test.el --eval \(ert-run-tests-batch-and-exit\) returned exit code 1
make: *** [debian/rules:4: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I failed
gbp:error: 'debuild -i -I -us -uc' failed: it exited with 29

`

^ When importing latest commit.

This blocks https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1011594

**Comment by sten0** [comment]
I confirm that this was resolved by 3a84689 (which I tested) or earlier.  This bug can be closed.
